"""Added add_to_playlist option

Revision ID: 1d9d31809908
Revises: 32751b84d437
Create Date: 2025-03-05 19:20:05.678677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9d31809908'
down_revision = '32751b84d437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_playlist_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('spotify_playlist_id')

    # ### end Alembic commands ###
