"""Added add_to_playlist option

Revision ID: 32751b84d437
Revises: a0720168a314
Create Date: 2025-03-05 15:46:46.005831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32751b84d437'
down_revision = 'a0720168a314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_add_to_playlist', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('spotify_add_to_playlist')

    # ### end Alembic commands ###
