"""Added additional twitch field for monitored_channel

Revision ID: 4cbde52e0dd3
Revises: ab268b8ae21c
Create Date: 2025-03-02 14:07:31.696067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbde52e0dd3'
down_revision = 'ab268b8ae21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitch_monitored_channel', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_column('twitch_monitored_channel')

    # ### end Alembic commands ###
