"""Added is_live

Revision ID: 6ac35a2d4a06
Revises: 1d9d31809908
Create Date: 2025-03-05 21:25:33.485524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac35a2d4a06'
down_revision = '1d9d31809908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitch_monitored_channel_is_live', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('twitch_monitored_channel_is_live')

    # ### end Alembic commands ###
