"""Changed layout of DB

Revision ID: 8f465a7fd63f
Revises: 4cbde52e0dd3
Create Date: 2025-03-03 18:29:54.393761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f465a7fd63f'
down_revision = '4cbde52e0dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index('twitch_user_id')
        batch_op.drop_index('user_id')
        batch_op.drop_index('user_uri')

    op.drop_table('user_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_uri', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('twitch_user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('spotify_access_token', sa.BLOB(), nullable=True),
    sa.Column('spotify_refresh_token', sa.BLOB(), nullable=True),
    sa.Column('spotify_token_expiration', mysql.DATETIME(), nullable=True),
    sa.Column('twitch_access_token', sa.BLOB(), nullable=True),
    sa.Column('twitch_refresh_token', sa.BLOB(), nullable=True),
    sa.Column('twitch_token_expiration', mysql.DATETIME(), nullable=True),
    sa.Column('current_playing_song_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('song_played_at', mysql.DATETIME(), nullable=True),
    sa.Column('spotify_scopes', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('current_playing_song_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('current_playing_song_artist', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('current_playing_song_uri', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('twitch_user_login', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('twitch_monitored_channel', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index('user_uri', ['user_uri'], unique=True)
        batch_op.create_index('user_id', ['user_id'], unique=True)
        batch_op.create_index('twitch_user_id', ['twitch_user_id'], unique=True)

    # ### end Alembic commands ###
