"""Added additional twitch field for user login

Revision ID: ab268b8ae21c
Revises: 25f1e85191ed
Create Date: 2025-03-02 12:17:16.384354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab268b8ae21c'
down_revision = '25f1e85191ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitch_user_login', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_column('twitch_user_login')

    # ### end Alembic commands ###
